using System.Data;
using Microsoft.EntityFrameworkCore;

namespace ArielVertex.Infrastructure.Persistence;

/// <summary>
/// Applies small, idempotent upgrades for databases created with EnsureCreated. EnsureCreated
/// does not evolve an existing schema when entity properties or modules are added.
/// </summary>
internal static class DatabaseSchemaUpgrader
{
    public static async Task ApplyAsync(AppDbContext db, CancellationToken cancellationToken = default)
    {
        var provider = db.Database.ProviderName ?? string.Empty;

        if (provider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
        {
            await UpgradeSqliteAsync(db, cancellationToken);
            return;
        }

        if (provider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "Users"
                    ADD COLUMN IF NOT EXISTS "ProfileManagedLocally" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE "Users"
                    ADD COLUMN IF NOT EXISTS "ManagerManagedLocally" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE "Users"
                    ADD COLUMN IF NOT EXISTS "IsHelpdeskSupport" boolean NOT NULL DEFAULT FALSE;

                ALTER TABLE "ReviewMeetings"
                    ADD COLUMN IF NOT EXISTS "ResponseStatus" integer NOT NULL DEFAULT 0;
                ALTER TABLE "ReviewMeetings"
                    ADD COLUMN IF NOT EXISTS "RespondedAt" timestamp with time zone NULL;

                ALTER TABLE "Promotions"
                    ADD COLUMN IF NOT EXISTS "RecommendationType" integer NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS "AppraisalCycles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_AppraisalCycles" PRIMARY KEY,
                    "Name" character varying(120) NOT NULL,
                    "StartDate" timestamp with time zone NOT NULL,
                    "EndDate" timestamp with time zone NOT NULL,
                    "Status" integer NOT NULL,
                    "CreatedById" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_AppraisalCycles_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AppraisalCycles_CreatedById" ON "AppraisalCycles" ("CreatedById");

                CREATE TABLE IF NOT EXISTS "Appraisals" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Appraisals" PRIMARY KEY,
                    "Stage" integer NOT NULL,
                    "SelfRating" numeric(3,2) NULL,
                    "SelfComments" character varying(4000) NULL,
                    "SelfSubmittedAt" timestamp with time zone NULL,
                    "ManagerRating" numeric(3,2) NULL,
                    "ManagerComments" character varying(4000) NULL,
                    "ManagerReviewedAt" timestamp with time zone NULL,
                    "FinalRating" numeric(3,2) NULL,
                    "ReleasedAt" timestamp with time zone NULL,
                    "CycleId" integer NOT NULL,
                    "EmployeeId" integer NOT NULL,
                    "ManagerId" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_Appraisals_AppraisalCycles_CycleId" FOREIGN KEY ("CycleId") REFERENCES "AppraisalCycles" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Appraisals_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Appraisals_Users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Appraisals_CycleId_EmployeeId" ON "Appraisals" ("CycleId", "EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Appraisals_EmployeeId" ON "Appraisals" ("EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Appraisals_ManagerId" ON "Appraisals" ("ManagerId");

                CREATE TABLE IF NOT EXISTS "Goals" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Goals" PRIMARY KEY,
                    "Title" character varying(160) NOT NULL,
                    "Description" character varying(2000) NOT NULL,
                    "Category" character varying(80) NOT NULL,
                    "Weightage" integer NOT NULL,
                    "Progress" integer NOT NULL,
                    "TargetDate" timestamp with time zone NOT NULL,
                    "Status" integer NOT NULL,
                    "EmployeeId" integer NOT NULL,
                    "AssignedById" integer NULL,
                    "CycleId" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_Goals_AppraisalCycles_CycleId" FOREIGN KEY ("CycleId") REFERENCES "AppraisalCycles" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Goals_Users_AssignedById" FOREIGN KEY ("AssignedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Goals_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_Goals_AssignedById" ON "Goals" ("AssignedById");
                CREATE INDEX IF NOT EXISTS "IX_Goals_CycleId" ON "Goals" ("CycleId");
                CREATE INDEX IF NOT EXISTS "IX_Goals_EmployeeId" ON "Goals" ("EmployeeId");

                CREATE TABLE IF NOT EXISTS "Promotions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Promotions" PRIMARY KEY,
                    "EmployeeId" integer NOT NULL,
                    "CurrentDesignation" character varying(120) NOT NULL,
                    "ProposedDesignation" character varying(120) NOT NULL,
                    "CurrentSalary" numeric(14,2) NULL,
                    "ProposedSalary" numeric(14,2) NULL,
                    "Justification" character varying(2000) NOT NULL,
                    "Stage" integer NOT NULL,
                    "RecommendationType" integer NOT NULL DEFAULT 0,
                    "DecisionNote" character varying(2000) NULL,
                    "RecommendedById" integer NULL,
                    "ValidatedAt" timestamp with time zone NULL,
                    "ApprovedAt" timestamp with time zone NULL,
                    "CompletedAt" timestamp with time zone NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_Promotions_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Promotions_Users_RecommendedById" FOREIGN KEY ("RecommendedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_Promotions_EmployeeId" ON "Promotions" ("EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Promotions_RecommendedById" ON "Promotions" ("RecommendedById");

                CREATE TABLE IF NOT EXISTS "TrainingRecommendations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_TrainingRecommendations" PRIMARY KEY,
                    "EmployeeId" integer NOT NULL,
                    "SkillGap" character varying(160) NOT NULL,
                    "RecommendedTraining" character varying(200) NOT NULL,
                    "DurationMonths" integer NOT NULL,
                    "Status" integer NOT NULL,
                    "Source" character varying(20) NOT NULL,
                    "CreatedById" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_TrainingRecommendations_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_TrainingRecommendations_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_TrainingRecommendations_CreatedById" ON "TrainingRecommendations" ("CreatedById");
                CREATE INDEX IF NOT EXISTS "IX_TrainingRecommendations_EmployeeId" ON "TrainingRecommendations" ("EmployeeId");

                CREATE TABLE IF NOT EXISTS "PettyCashEntries" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_PettyCashEntries" PRIMARY KEY,
                    "Date" timestamp with time zone NOT NULL,
                    "Particulars" character varying(200) NOT NULL,
                    "OpeningBalance" numeric(12,2) NOT NULL DEFAULT 0,
                    "Credit" numeric(12,2) NOT NULL DEFAULT 0,
                    "Debit" numeric(12,2) NOT NULL DEFAULT 0,
                    "Balance" numeric(12,2) NOT NULL DEFAULT 0,
                    "Notes" character varying(500) NULL,
                    "CreatedById" integer NOT NULL,
                    "Status" integer NOT NULL DEFAULT 1,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_PettyCashEntries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users"("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_PettyCashEntries_Date" ON "PettyCashEntries" ("Date");

                CREATE TABLE IF NOT EXISTS "HelpdeskTickets" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_HelpdeskTickets" PRIMARY KEY,
                    "Subject" character varying(200) NOT NULL,
                    "Description" character varying(4000) NOT NULL,
                    "Category" integer NOT NULL,
                    "Priority" integer NOT NULL,
                    "Status" integer NOT NULL,
                    "RaisedById" integer NOT NULL,
                    "AssignedToId" integer NULL,
                    "Resolution" character varying(4000) NULL,
                    "ResolvedAt" timestamp with time zone NULL,
                    "ClosedAt" timestamp with time zone NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_HelpdeskTickets_Users_RaisedById" FOREIGN KEY ("RaisedById") REFERENCES "Users"("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_HelpdeskTickets_Users_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users"("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskTickets_Status" ON "HelpdeskTickets" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskTickets_RaisedById" ON "HelpdeskTickets" ("RaisedById");

                CREATE TABLE IF NOT EXISTS "HelpdeskCategoryAssignments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_HelpdeskCategoryAssignments" PRIMARY KEY,
                    "Category" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_HelpdeskCategoryAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE SET NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_HelpdeskCategoryAssignments_Category" ON "HelpdeskCategoryAssignments" ("Category");
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskCategoryAssignments_UserId" ON "HelpdeskCategoryAssignments" ("UserId");

                CREATE TABLE IF NOT EXISTS "Assets" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Assets" PRIMARY KEY,
                    "Name" character varying(200) NOT NULL,
                    "Description" character varying(2000) NOT NULL,
                    "Category" integer NOT NULL,
                    "SerialNumber" character varying(100) NULL,
                    "PurchaseDate" timestamp with time zone NULL,
                    "PurchasePrice" numeric(12,2) NULL,
                    "Condition" integer NOT NULL,
                    "Status" integer NOT NULL,
                    "AssignedToId" integer NULL,
                    "AssignedAt" timestamp with time zone NULL,
                    "ReturnedAt" timestamp with time zone NULL,
                    "CreatedById" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_Assets_Users_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users"("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Assets_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users"("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_Assets_Status" ON "Assets" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_Assets_AssignedToId" ON "Assets" ("AssignedToId");

                CREATE TABLE IF NOT EXISTS "AssetRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_AssetRequests" PRIMARY KEY,
                    "Subject" character varying(200) NOT NULL,
                    "Description" character varying(4000) NOT NULL,
                    "RequestType" integer NOT NULL,
                    "AssetId" integer NULL,
                    "TargetUserId" integer NULL,
                    "Quantity" integer NOT NULL DEFAULT 1,
                    "EstimatedCost" numeric(12,2) NULL,
                    "Vendor" character varying(200) NULL,
                    "Status" integer NOT NULL,
                    "RaisedById" integer NOT NULL,
                    "ApproverId" integer NULL,
                    "DecidedAt" timestamp with time zone NULL,
                    "DecisionNote" character varying(2000) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "FK_AssetRequests_Users_RaisedById" FOREIGN KEY ("RaisedById") REFERENCES "Users"("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AssetRequests_Users_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES "Users"("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_AssetRequests_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES "Users"("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_AssetRequests_Assets_AssetId" FOREIGN KEY ("AssetId") REFERENCES "Assets"("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_Status" ON "AssetRequests" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_RaisedById" ON "AssetRequests" ("RaisedById");
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_AssetId" ON "AssetRequests" ("AssetId");

                ALTER TABLE "AssetRequests" ADD COLUMN IF NOT EXISTS "TargetUserId" integer NULL;
                ALTER TABLE "AssetRequests" ADD CONSTRAINT IF NOT EXISTS "FK_AssetRequests_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES "Users"("Id") ON DELETE SET NULL;
                """,
                cancellationToken);
        }
    }

    private static async Task UpgradeSqliteAsync(AppDbContext db, CancellationToken cancellationToken)
    {
        var connection = db.Database.GetDbConnection();
        var closeWhenDone = connection.State != ConnectionState.Open;

        if (closeWhenDone) await connection.OpenAsync(cancellationToken);

        try
        {
            var columns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var command = connection.CreateCommand())
            {
                command.CommandText = """PRAGMA table_info("ReviewMeetings");""";
                await using var reader = await command.ExecuteReaderAsync(cancellationToken);
                while (await reader.ReadAsync(cancellationToken))
                    columns.Add(reader.GetString(1));
            }

            if (!columns.Contains("ResponseStatus"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "ReviewMeetings" ADD COLUMN "ResponseStatus" INTEGER NOT NULL DEFAULT 0;""",
                    cancellationToken);

            if (!columns.Contains("RespondedAt"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "ReviewMeetings" ADD COLUMN "RespondedAt" TEXT NULL;""",
                    cancellationToken);

            var userColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var command = connection.CreateCommand())
            {
                command.CommandText = """PRAGMA table_info("Users");""";
                await using var reader = await command.ExecuteReaderAsync(cancellationToken);
                while (await reader.ReadAsync(cancellationToken))
                    userColumns.Add(reader.GetString(1));
            }

            if (!userColumns.Contains("ProfileManagedLocally"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "Users" ADD COLUMN "ProfileManagedLocally" INTEGER NOT NULL DEFAULT 0;""",
                    cancellationToken);

            if (!userColumns.Contains("ManagerManagedLocally"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "Users" ADD COLUMN "ManagerManagedLocally" INTEGER NOT NULL DEFAULT 0;""",
                    cancellationToken);

            if (!userColumns.Contains("IsHelpdeskSupport"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "Users" ADD COLUMN "IsHelpdeskSupport" INTEGER NOT NULL DEFAULT 0;""",
                    cancellationToken);

            var promotionColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var command = connection.CreateCommand())
            {
                command.CommandText = """PRAGMA table_info("Promotions");""";
                await using var reader = await command.ExecuteReaderAsync(cancellationToken);
                while (await reader.ReadAsync())
                    promotionColumns.Add(reader.GetString(1));
            }

            if (!promotionColumns.Contains("RecommendationType"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "Promotions" ADD COLUMN "RecommendationType" INTEGER NOT NULL DEFAULT 0;""",
                    cancellationToken);

            var assetRequestColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            await using (var command = connection.CreateCommand())
            {
                command.CommandText = """PRAGMA table_info("AssetRequests");""";
                await using var reader = await command.ExecuteReaderAsync(cancellationToken);
                while (await reader.ReadAsync(cancellationToken))
                    assetRequestColumns.Add(reader.GetString(1));
            }

            if (!assetRequestColumns.Contains("TargetUserId"))
                await db.Database.ExecuteSqlRawAsync(
                    """ALTER TABLE "AssetRequests" ADD COLUMN "TargetUserId" INTEGER NULL;""",
                    cancellationToken);

            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "AppraisalCycles" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AppraisalCycles" PRIMARY KEY AUTOINCREMENT,
                    "Name" TEXT NOT NULL,
                    "StartDate" TEXT NOT NULL,
                    "EndDate" TEXT NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "CreatedById" INTEGER NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_AppraisalCycles_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AppraisalCycles_CreatedById" ON "AppraisalCycles" ("CreatedById");

                CREATE TABLE IF NOT EXISTS "Appraisals" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_Appraisals" PRIMARY KEY AUTOINCREMENT,
                    "Stage" INTEGER NOT NULL,
                    "SelfRating" TEXT NULL,
                    "SelfComments" TEXT NULL,
                    "SelfSubmittedAt" TEXT NULL,
                    "ManagerRating" TEXT NULL,
                    "ManagerComments" TEXT NULL,
                    "ManagerReviewedAt" TEXT NULL,
                    "FinalRating" TEXT NULL,
                    "ReleasedAt" TEXT NULL,
                    "CycleId" INTEGER NOT NULL,
                    "EmployeeId" INTEGER NOT NULL,
                    "ManagerId" INTEGER NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_Appraisals_AppraisalCycles_CycleId" FOREIGN KEY ("CycleId") REFERENCES "AppraisalCycles" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Appraisals_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Appraisals_Users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Appraisals_CycleId_EmployeeId" ON "Appraisals" ("CycleId", "EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Appraisals_EmployeeId" ON "Appraisals" ("EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Appraisals_ManagerId" ON "Appraisals" ("ManagerId");

                CREATE TABLE IF NOT EXISTS "Goals" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_Goals" PRIMARY KEY AUTOINCREMENT,
                    "Title" TEXT NOT NULL,
                    "Description" TEXT NOT NULL,
                    "Category" TEXT NOT NULL,
                    "Weightage" INTEGER NOT NULL,
                    "Progress" INTEGER NOT NULL,
                    "TargetDate" TEXT NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "EmployeeId" INTEGER NOT NULL,
                    "AssignedById" INTEGER NULL,
                    "CycleId" INTEGER NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_Goals_AppraisalCycles_CycleId" FOREIGN KEY ("CycleId") REFERENCES "AppraisalCycles" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Goals_Users_AssignedById" FOREIGN KEY ("AssignedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Goals_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_Goals_AssignedById" ON "Goals" ("AssignedById");
                CREATE INDEX IF NOT EXISTS "IX_Goals_CycleId" ON "Goals" ("CycleId");
                CREATE INDEX IF NOT EXISTS "IX_Goals_EmployeeId" ON "Goals" ("EmployeeId");

                CREATE TABLE IF NOT EXISTS "Promotions" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_Promotions" PRIMARY KEY AUTOINCREMENT,
                    "EmployeeId" INTEGER NOT NULL,
                    "CurrentDesignation" TEXT NOT NULL,
                    "ProposedDesignation" TEXT NOT NULL,
                    "CurrentSalary" TEXT NULL,
                    "ProposedSalary" TEXT NULL,
                    "Justification" TEXT NOT NULL,
                    "Stage" INTEGER NOT NULL,
                    "RecommendationType" INTEGER NOT NULL DEFAULT 0,
                    "DecisionNote" TEXT NULL,
                    "RecommendedById" INTEGER NULL,
                    "ValidatedAt" TEXT NULL,
                    "ApprovedAt" TEXT NULL,
                    "CompletedAt" TEXT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_Promotions_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_Promotions_Users_RecommendedById" FOREIGN KEY ("RecommendedById") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_Promotions_EmployeeId" ON "Promotions" ("EmployeeId");
                CREATE INDEX IF NOT EXISTS "IX_Promotions_RecommendedById" ON "Promotions" ("RecommendedById");

                CREATE TABLE IF NOT EXISTS "TrainingRecommendations" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_TrainingRecommendations" PRIMARY KEY AUTOINCREMENT,
                    "EmployeeId" INTEGER NOT NULL,
                    "SkillGap" TEXT NOT NULL,
                    "RecommendedTraining" TEXT NOT NULL,
                    "DurationMonths" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "Source" TEXT NOT NULL,
                    "CreatedById" INTEGER NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_TrainingRecommendations_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_TrainingRecommendations_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_TrainingRecommendations_CreatedById" ON "TrainingRecommendations" ("CreatedById");
                CREATE INDEX IF NOT EXISTS "IX_TrainingRecommendations_EmployeeId" ON "TrainingRecommendations" ("EmployeeId");

                CREATE TABLE IF NOT EXISTS "PettyCashEntries" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_PettyCashEntries" PRIMARY KEY AUTOINCREMENT,
                    "Date" TEXT NOT NULL,
                    "Particulars" TEXT NOT NULL,
                    "OpeningBalance" TEXT NOT NULL DEFAULT '0',
                    "Credit" TEXT NOT NULL DEFAULT '0',
                    "Debit" TEXT NOT NULL DEFAULT '0',
                    "Balance" TEXT NOT NULL DEFAULT '0',
                    "Notes" TEXT NULL,
                    "CreatedById" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL DEFAULT 1,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_PettyCashEntries_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_PettyCashEntries_Date" ON "PettyCashEntries" ("Date");

                CREATE TABLE IF NOT EXISTS "HelpdeskTickets" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_HelpdeskTickets" PRIMARY KEY AUTOINCREMENT,
                    "Subject" TEXT NOT NULL,
                    "Description" TEXT NOT NULL,
                    "Category" INTEGER NOT NULL,
                    "Priority" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "RaisedById" INTEGER NOT NULL,
                    "AssignedToId" INTEGER NULL,
                    "Resolution" TEXT NULL,
                    "ResolvedAt" TEXT NULL,
                    "ClosedAt" TEXT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_HelpdeskTickets_Users_RaisedById" FOREIGN KEY ("RaisedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_HelpdeskTickets_Users_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskTickets_Status" ON "HelpdeskTickets" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskTickets_RaisedById" ON "HelpdeskTickets" ("RaisedById");

                CREATE TABLE IF NOT EXISTS "HelpdeskCategoryAssignments" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_HelpdeskCategoryAssignments" PRIMARY KEY AUTOINCREMENT,
                    "Category" INTEGER NOT NULL,
                    "UserId" INTEGER NOT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_HelpdeskCategoryAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_HelpdeskCategoryAssignments_Category" ON "HelpdeskCategoryAssignments" ("Category");
                CREATE INDEX IF NOT EXISTS "IX_HelpdeskCategoryAssignments_UserId" ON "HelpdeskCategoryAssignments" ("UserId");

                CREATE TABLE IF NOT EXISTS "Assets" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_Assets" PRIMARY KEY AUTOINCREMENT,
                    "Name" TEXT NOT NULL,
                    "Description" TEXT NOT NULL,
                    "Category" INTEGER NOT NULL,
                    "SerialNumber" TEXT NULL,
                    "PurchaseDate" TEXT NULL,
                    "PurchasePrice" TEXT NULL,
                    "Condition" INTEGER NOT NULL,
                    "Status" INTEGER NOT NULL,
                    "AssignedToId" INTEGER NULL,
                    "AssignedAt" TEXT NULL,
                    "ReturnedAt" TEXT NULL,
                    "CreatedById" INTEGER NOT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_Assets_Users_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_Assets_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS "IX_Assets_Status" ON "Assets" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_Assets_AssignedToId" ON "Assets" ("AssignedToId");

                CREATE TABLE IF NOT EXISTS "AssetRequests" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_AssetRequests" PRIMARY KEY AUTOINCREMENT,
                    "Subject" TEXT NOT NULL,
                    "Description" TEXT NOT NULL,
                    "RequestType" INTEGER NOT NULL,
                    "AssetId" INTEGER NULL,
                    "TargetUserId" INTEGER NULL,
                    "Quantity" INTEGER NOT NULL DEFAULT 1,
                    "EstimatedCost" TEXT NULL,
                    "Vendor" TEXT NULL,
                    "Status" INTEGER NOT NULL,
                    "RaisedById" INTEGER NOT NULL,
                    "ApproverId" INTEGER NULL,
                    "DecidedAt" TEXT NULL,
                    "DecisionNote" TEXT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "UpdatedAt" TEXT NULL,
                    CONSTRAINT "FK_AssetRequests_Users_RaisedById" FOREIGN KEY ("RaisedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_AssetRequests_Users_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_AssetRequests_Users_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
                    CONSTRAINT "FK_AssetRequests_Assets_AssetId" FOREIGN KEY ("AssetId") REFERENCES "Assets" ("Id") ON DELETE SET NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_Status" ON "AssetRequests" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_RaisedById" ON "AssetRequests" ("RaisedById");
                CREATE INDEX IF NOT EXISTS "IX_AssetRequests_AssetId" ON "AssetRequests" ("AssetId");
                """,
                cancellationToken);
        }
        finally
        {
            if (closeWhenDone) await connection.CloseAsync();
        }
    }
}
